### ISSUE TITLE
KSP TypeElementSymbolProcessorProvider call `visitClass(...)` only on changed classes with `ksp.incremental=true`

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#10253]
To reproduce problem you can run sample project by instruction here: https://github.com/micronaut-projects/micronaut-openapi/issues/1345

With first running - all works fine, but when you change only controller class and re-run annotation processing - micronaut ksp processor won't call method `visit` on class with annotation OpenAPIDefinition. The same situation if you have 2 controllers and modified only one - TypeElementSymbolProcessorProvider will call `visitClass(...)` method only for modified controller.

### Version

4.2.1

**Comment by altro3** [comment]
@dstepanov WDYT? Is it bug or KSP feature?

**Comment by altro3** [comment]
@dstepanov I found documentation about incremental KSP processing: https://kotlinlang.org/docs/ksp-incremental.html

So, as I understand, we can't use micronaut-openapi with `ksp.incremental = true`...

@dstepanov What do you think about this? Should I add a clarification to the micronaut-openapi documentation that micronaut-openapi (and maybe the entire micronaut) will not work correctly with KSP incremental processing

**Comment by dstepanov** [comment]
Can you try to use `visitGeneratedFile`, that one is producing aggregated file:
```
    override fun visitMetaInfFile(path: String, vararg originatingElements: Element): Optional<GeneratedFile> {
        val elements = normalizePath("META-INF/$path")
        return Optional.of(KotlinVisitorContext.KspGeneratedFile(environment, elements, getNativeElements(originatingElements)))
    }

    override fun visitGeneratedFile(path: String): Optional<GeneratedFile> {
        val elements = normalizePath(path)
        return Optional.of(KotlinVisitorContext.KspGeneratedFile(environment, elements, Dependencies(aggregating = true, sources = emptyArray())))
    }
```

**Comment by graemerocher** [comment]
OpenAPI is an aggregating processor (processing multiple sources to produce one file) so yeah we need to somehow make sure when the file is written `aggregating = true` and all the sources are provided. This may require changes in the OpenAPI module and core

**Comment by dstepanov** [comment]
I guess we can create a context per visitor and extract the aggregate info from there

**Comment by altro3** [comment]
sorry, don't understand what I need to change to fix it

**Comment by dstepanov** [comment]
You can try to use `visitGeneratedFile` if it helps

**Comment by altro3** [comment]
I think,: in principle, this processing cannot be incremental. Here is an explicit example that cannot be handled correctly with incremental processing:

We have 2 controller classes, the first one describes 5 endpoints, and the second one does the same. We have generated an openapi. Everything is OK here, there will be 10 endpoints.

Next, we remove 2 endpoints from the first class, and add 3 other endpoints in the same first class.

With incremental processing, we will get not 11 endpoints, as we should, but 13 endpoints. Because it will be impossible to understand that some of the endpoints have been deleted, because during incremental processing we only see the changed classes, but we do not know from the swagger file in which of the controllers the endpoints were described.

@dstepanov what do you think?

**Comment by graemerocher** [comment]
Most Incremental compilers (IntelliJ and Gradle compiler) are smart enough to understand when classes are deleted a full recompile is needed.

**Comment by altro3** [comment]
True, but it's not about deleting classes, it's about deleting endpoints. And the endpoint is a method, not a class. How can openapi understand which methods have been deleted/paths changed?

I will answer - no way

**Comment by graemerocher** [comment]
it is not openapi that has to understand, it is the incremental compiler which should be smart enough to detect the deletion and trigger a full recompile

**Comment by graemerocher** [comment]
also keep in mind that the swagger file always has to be rebuilt from all the originating sources. The point is not to incrementally create the swagger file. The point is ensure that if the user modifies any other source file that doesn't contribute to the swagger them those are compiled incrementally and a full rebuild of the other files is not necessary.

**Comment by altro3** [comment]
I think you misunderstood me: I'm talking about a case where a user deletes several endpoints from a controller class, but does not delete the class itself. That is, it is a file change, not a deletion. Because of this, the incremental compiler realizes that only one class has changed and recompiles only this class.

Let's say that there was already a compilation before and the swagger file has already been generated. Thus, during incremental compilation, we will receive only the endpoints from the modified class at the input.

Even if I load the data from the previous swagger file first, I won't be able to figure out what changed during recompilation. I can understand that new endpoints have appeared or that old endpoints have changed. BUT I can't figure out in any way that some of the endpoints have been deleted.

**Comment by dstepanov** [comment]
I think I can fix it. We need to use a different create file call for aggregated visitors

**Comment by davidsonnabend** [comment]
Are you sure that the problem is fixed?
This change was released with Micronaut Core 4.3.6, so it should be part of Micronaut 4.3.3, right?

I updated the [example application](https://github.com/davidsonnabend/micronaut-swaggerui-versioned-api-bug) used to demonstrate the bug #1345 to Micronaut 4.3.3 and can still reproduce the false behavior.

Did I missed something?

**Comment by altro3** [comment]
By the way, I also checked the latest version. The problem remains the same - the visitor visits only the modified files, because of this, the openapi file is not being built correctly
