### ISSUE TITLE
Errors On Main Web Site

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-core#10515]
### Issue description

See the attached image.

`       GET https://forms.hsforms.com/embed/v3/form/4547412/a7b3ddfa-64b0-47fd-8358-45fa6a09456a/json?hs_static_app=forms-embed&hs_static_app_version=1.4708&X-HubSpot-Static-App-Info=forms-embed-1.4708&hutk=af91bf899f6aff765a9b5773dccdb8c4 404 (Not Found)`

`Attestation check for Topics on https://micronaut.io/ failed.`

![Screenshot 2024-02-19 at 12 48 48 PM](https://github.com/micronaut-projects/micronaut-core/assets/15482/50d4dd77-3140-4557-adb0-4b27ef22682f)

**Comment by wiesej** [comment]
This has been fixed. Thank you

**Comment by jeffscottbrown** [comment]
> This has been fixed. Thank you

FYI... It is possible that I am seeing cached content but the errors are still being logged in the browser console.

**Comment by jeffscottbrown** [comment]
FYI... It looks like the Attestation error may be gone now and the HubSpot error is still being logged.

**Comment by wiesej** [comment]
Removed the plugin and believe issue is resolved.
