### ISSUE TITLE
Rxjava2 Observable Type not serializable in micronaut 4.9.x, was working in 4.8.x.

### ISSUE THREAD

**Issue by subash89** [micronaut-projects/micronaut-core#12154]
### Expected Behavior

rxjava 2 Observable type should be serializable in micronaut 4.9.x

### Actual Behaviour

Fails to serialize rxjava2 Observable. But rxjava2 'Single' works.

### Steps To Reproduce

I have a simple micronaut jaxrs app created from mn tool. And I updated the Resource class [1] to have two following apis.

When invoked /pets/simple works as expected.
When invoked /pets/observable it fails with following error [2]
Note that in the pom I added micronaut-rxjava2 dependency also.

But if I just change the pom's micronaut-parent to 4.8.3, it just works.(meaning /pets/observable also gives me success response). Looks like there is a breaking change introduced ? or any workaround for this. Our teams have lot of rxjava2 Observable usage.

Also rxjava Single also works fine. Only Observable or Flowable types failing with this error.

And I attached the project here. [
[micronaut-jaxrs-jdbc-maven-java.zip](https://github.com/user-attachments/files/22951204/micronaut-jaxrs-jdbc-maven-java.zip)
](url)

[1]
```java
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.serde.annotation.Serdeable;

import jakarta.validation.constraints.NotBlank;

@Serdeable
@Introspected// <1>
public class NameDto {

    @NonNull
    @NotBlank
    private final String name;

    public NameDto(@NonNull String name) {
        this.name = name;
    }

    @NonNull
    public String getName() {
        return name;
    }
}
```

```java
import io.reactivex.Observable;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;


@Path("/pets") // <1>
class PetResource {

    @GET
    @Path("simple")
    public NameDto all() { // <4>
        return new NameDto("Fluffy");
    }

    @GET
    @Path("observable")
    public Observable<NameDto> allOb() { // <4>
        return Observable.just(new NameDto("Fluffy"));
    }
}
```

[2]

10:02:33.567 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 427ms. Server Running: http://localhost:8080 10:02:36.371 [virtual-executor--776552351] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error encoding object [io.micronaut.core.async.propagation.ReactivePropagation$1@6edd7ace] to JSON: No serializable introspection present for type . Consider adding Serdeable. Serializable annotate to type . Alternatively if you are not in control of the project's source code, you can use @SerdeImport(.class) to enable serialization of this type. io.micronaut.http.codec.CodecException: Error encoding object [io.micronaut.core.async.propagation.ReactivePropagation$1@6edd7ace] to JSON: No serializable introspection present for type . Consider adding Serdeable. Serializable annotate to type . Alternatively if you are not in control of the project's source code, you can use @SerdeImport(.class) to enable serialization of this type. at io.micronaut.json.body.JsonMessageHandler.writePiece(JsonMessageHandler.java:156) at io.micronaut.http.body.ResponseBodyWriter.write(ResponseBodyWriter.java:62) at io.micronaut.http.netty.body.NettyJsonHandler.write(NettyJsonHandler.java:132) at io.micronaut.jaxrs.common.JaxRsGenericEntityMessageBodyWriter$2.writeInner0(JaxRsGenericEntityMessageBodyWriter.java:164) at io.micronaut.jaxrs.common.JaxRsGenericEntityMessageBodyWriter$ByteBodyState.writeInner(JaxRsGenericEntityMessageBodyWriter.java:343) at io.micronaut.jaxrs.common.JaxRsGenericEntityMessageBodyWriter$ByteBodyState.run(JaxRsGenericEntityMessageBodyWriter.java:293) at io.micronaut.jaxrs.common.JaxRsGenericEntityMessageBodyWriter.write(JaxRsGenericEntityMessageBodyWriter.java:168) at io.micronaut.jaxrs.common.JaxRsGenericEntityMessageBodyWriter.write(JaxRsGenericEntityMessageBodyWriter.java:54) at io.micronaut.http.server.ResponseLifecycle.buildFinalResponse(ResponseLifecycle.java:331) at io.micronaut.http.server.ResponseLifecycle.lambda$buildFinalResponse$7(ResponseLifecycle.java:326) at io.micronaut.core.execution.ExecutionFlow.lambda$async$0(ExecutionFlow.java:92) at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:232) at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) at java.base/java.lang.VirtualThread.run(VirtualThread.java:329) Caused by: io.micronaut.serde.exceptions.SerdeException: No serializable introspection present for type . Consider adding Serdeable. Serializable annotate to type . Alternatively if you are not in control of the project's source code, you can use @SerdeImport(.class) to enable serialization of this type. at io.micronaut.serde.support.serializers.RuntimeTypeSerializer.lambda$getSerializer$0(RuntimeTypeSerializer.java:135) at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) at io.micronaut.serde.support.serializers.RuntimeTypeSerializer.getSerializer(RuntimeTypeSerializer.java:131) at io.micronaut.serde.support.serializers.RuntimeTypeSerializer.serialize(RuntimeTypeSerializer.java:76) at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:246) at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue0(JacksonJsonMapper.java:228) at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue0(JacksonJsonMapper.java:223) at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:328) at io.micronaut.json.body.JsonMessageHandler.lambda$writePiece$0(JsonMessageHandler.java:154) at io.micronaut.http.netty.body.NettyByteBodyFactory.buffer(NettyByteBodyFactory.java:77) at io.micronaut.json.body.JsonMessageHandler.writePiece(JsonMessageHandler.java:154) ... 13 common frames omitted Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No serializable introspection present for type . Consider adding Serdeable. Serializable annotate to type . Alternatively if you are not in control of the project's source code, you can use @SerdeImport(.class) to enable serialization of this type. at io.micronaut.serde.support.DefaultSerdeIntrospections.getSerializableIntrospection(DefaultSerdeIntrospections.java:111) at io.micronaut.serde.support.serializers.SerBean.<init>(SerBean.java:118) at io.micronaut.serde.support.serializers.ObjectSerializer.lambda$getSerializableBean$0(ObjectSerializer.java:165) at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:79) at io.micronaut.serde.support.serializers.ObjectSerializer.getSerializableBean(ObjectSerializer.java:170) at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecificInternal(ObjectSerializer.java:107) at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:99) at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:243) ... 19 common frames omitted 

### Environment Information

JDK 21

### Version

4.9.3

**Comment by subash89** [comment]
@sdelamo  @graemerocher  it would be great if you can prioritize this to 4.10.3 release if possible. This is a breaking change that blocks users on our end who uses rxjava2 Observable as response type.

**Comment by graemerocher** [comment]
@yawkat please take a look

**Comment by subash89** [comment]
@yawkat  just wanted to check whether this can be expected to fix in 4.10.5.

**Comment by subash89** [comment]
@graemerocher  @yawkat  just a gentle reminder on whether we can expect a release from this. This blocks many of our users. Appreciate your input.

**Comment by dstepanov** [comment]
I think you are missing `micronaut-rxjava2`

**Comment by sdelamo** [comment]
@dstepanov he has 

```
    <dependency>
      <groupId>io.micronaut.rxjava2</groupId>
      <artifactId>micronaut-rxjava2</artifactId>
    </dependency>
```

in his sample application pom.

**Comment by graemerocher** [comment]
@dstepanov can you take a look in @yawkat 's absence. Thanks.

**Comment by subash89** [comment]
@dstepanov @yawkat May I know when 4.8.10 is scheduled ? Hope this ticket will be part of the 4.8.10. Thanks

**Comment by subash89** [comment]
@graemerocher  @dstepanov  Is there anything I can do on my end that can work around this until 4.10.8 is released ?

**Comment by subash89** [comment]
@graemerocher  @sdelamo  @dstepanov Looks like this was not included for 4.10.8 as well :-(.  Can you pls include this to at least for 4.10.9 release ? And any workaround fix we can use for this?

**Comment by graemerocher** [comment]
Added a reproducer https://github.com/micronaut-projects/micronaut-rxjava2/pull/326

we will look into it

**Comment by yawkat** [comment]
btw as a workaround you can probably just annotate the controller with `@SingleResult`

**Comment by subash89** [comment]
@yawkat  @graemerocher  this fails for even /swagger-ui like endpoints. We cannot fix those with @SingleResult workaround even though it would work for other cases. I see this moved out from 4.10.9 release as well. Any chance of this getting included into 4.10.10.

**Comment by yawkat** [comment]
The swagger-ui thing is a separate issue that is fixed in 6.0.x https://github.com/micronaut-projects/micronaut-jaxrs/pull/622

**Comment by subash89** [comment]
@yawkat  #622 is still shows in open state.  Will you be planning to fix this original regression bug in next release ? This is opened so far for 5 months.
