### ISSUE TITLE
Problem with tracing after upgrade to 1.2.0

### ISSUE THREAD

**Issue by typhoon2k** [micronaut-projects/micronaut-core#2051]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

We just tried to upgrade our application (it is a graphql app, but that doesn't play any role here) from micronaut 1.1.4 to 1.2.0 and observed problem with tracing - span for new server request is referencing span of previous request. This behavior is observed, when both server requests are processed by the same thread.

Reason for that most likely is the change made in [this commit](https://github.com/micronaut-projects/micronaut-core/commit/ac26d9d1b271420358efa66a4489c9107264dffc#diff-8b07cb5e9e8bd19db2b4b5c32dec375d) > method onNext, where Scope is closed only when closedAfterNext is true. Previously it was *always* closed.

While debugging this problem we found out that tracer.activeSpan() returns span of previous request, which was processed by the same thread. As we know this span is used as a parent span for new span (unless ignoreActiveSpan() is used, when building new span). Therefore we get such behavior.

### Expected Behaviour

All scopes have to be closed after processing request.

### Actual Behaviour

Scope created in onNext method is not always closed.

### Environment Information

- **Operating System**: any
- **Micronaut Version:** 1.2.0
- **JDK Version:** 1.8

### Example Application

N/A

**Comment by graemerocher** [comment]
I have pushed a potential fix but lack an application that reproduces the error. Could you provide a sample that reproduces the problem?

If you could verify the fix using the snapshot that would help too. You can do so by adding the snapshot repo to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.2.1.BUILD-SNAPSHOT'
    }
}
```

**Comment by pfyod** [comment]
Thanks @graemerocher, your fix _seems_ to work. 

Unfortunately, it's not so easy to provide a sample that consistently reproduces the problem... We're still not exactly sure what _exactly_ triggers the bug (apart from opentracing changing the API and making everyone rewrite the tracing code).

In addition to the built in micronaut instrumentations we also use:

1. cxf-integration-tracing-opentracing (JAX-WS client tracing)
2. Custom GraphQL instrumentation
3. Redis instrumentaion (based on https://github.com/opentracing-contrib/java-redis-client)

Even with 2. and 3. disabled, the issue could still be reproduced just with jmeter spamming the `/health` endpoint and some background JAX-WS requests. I've created a sample repo with just micronaut and cxf-integration-tracing-opentracing: https://github.com/pfyod/micronaut-1.2.0-tracing, but it's very flaky.

**Comment by graemerocher** [comment]
Ok thanks for the sample seems to work for me too. Shame it is hard to put in place a test for this stuff..

**Comment by pfyod** [comment]
@graemerocher would it be possible to release micronaut-security 1.2.1 (or maybe as 1.2.2 now?) and add it to the BOM? Even though the issue marked as fixed/released in the milestone, the fix is only available if one adds the snapshot dependency.

**Comment by pfyod** [comment]
@graemerocher unfortunately, it does not look like it's completely fixed. I've updated the repository https://github.com/pfyod/micronaut-1.2.0-tracing with a minimal example + test. Essentially, when making two requests to `/health` and then to `/ping`, `/ping` becomes a child span of `/health` which is obviously not correct.
