### ISSUE TITLE
Recursive update during beans context initalization

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#2099]
In `1.2.0`. Sometimes **Recursive update** error happens when I start the context, usually when it's started in test environment during JUnit tests. Sometimes happens, sometimes not, I can for example change the Micronaut log level to get rid of it. It looks like some race condition. Can't provide an example because it apparently happens with my beans configuration which is currently quite complex.

I'm attaching the example caught on the debug level: [recursive-update.log](https://github.com/micronaut-projects/micronaut-core/files/3590215/recursive-update.log).

**Comment by l0co** [comment]
So, anyone? :)

The bug is in Micronaut way of using `computeIfAbsent()`. When I stop with breakpoint on the exception I have:

<details><summary>Detailed stacktrace</summary>
<p>

```
computeIfAbsent:1760, ConcurrentHashMap (java.util.concurrent) [2]
compute:733, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
computeIfAbsent:710, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
findConcreteCandidate:2126, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1898, DefaultBeanContext (io.micronaut.context)
getBean:1042, DefaultBeanContext (io.micronaut.context)
getBeanForConstructorArgument:989, AbstractBeanDefinition (io.micronaut.context)
build:-1, $JpaConfigurationDefinition (io.micronaut.configuration.hibernate.jpa)
build:113, BeanDefinitionDelegate (io.micronaut.context)
doCreateBean:1560, DefaultBeanContext (io.micronaut.context)
createAndRegisterSingleton:2279, DefaultBeanContext (io.micronaut.context)
getBeanForDefinition:1948, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1923, DefaultBeanContext (io.micronaut.context)
findBean:1062, DefaultBeanContext (io.micronaut.context)
findBean:589, DefaultBeanContext (io.micronaut.context)
matches:54, EntitiesInPackageCondition (io.micronaut.configuration.hibernate.jpa.condition)
matchesCustomConditions:325, RequiresCondition (io.micronaut.context)
processPostStartRequirements:206, RequiresCondition (io.micronaut.context)
matches:101, RequiresCondition (io.micronaut.context)
isEnabled:53, AbstractBeanContextConditional (io.micronaut.context)
isEnabled:89, AbstractBeanDefinition (io.micronaut.context)
lambda$findBeanCandidates$34:1388, DefaultBeanContext (io.micronaut.context)
test:-1, 1690101810 (io.micronaut.context.DefaultBeanContext$$Lambda$389)
accept:176, ReferencePipeline$2$1 (java.util.stream)
accept:195, ReferencePipeline$3$1 (java.util.stream)
accept:177, ReferencePipeline$2$1 (java.util.stream)
forEachFrom:1037, ConcurrentLinkedQueue (java.util.concurrent)
forEachRemaining:894, ConcurrentLinkedQueue$CLQSpliterator (java.util.concurrent)
copyInto:484, AbstractPipeline (java.util.stream)
wrapAndCopyInto:474, AbstractPipeline (java.util.stream)
evaluateSequential:913, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:578, ReferencePipeline (java.util.stream)
findBeanCandidates:1389, DefaultBeanContext (io.micronaut.context)
findBeanCandidates:241, DefaultApplicationContext (io.micronaut.context)
isCandidatePresent:2617, DefaultBeanContext (io.micronaut.context)
containsBean:570, DefaultBeanContext (io.micronaut.context)
containsBean:355, BeanDefinitionRegistry (io.micronaut.context)
matchesPresenceOfBeans:529, RequiresCondition (io.micronaut.context)
processPostStartRequirements:198, RequiresCondition (io.micronaut.context)
matches:101, RequiresCondition (io.micronaut.context)
isEnabled:53, AbstractBeanContextConditional (io.micronaut.context)
isEnabled:89, AbstractBeanDefinition (io.micronaut.context)
lambda$findBeanCandidates$34:1388, DefaultBeanContext (io.micronaut.context)
test:-1, 1690101810 (io.micronaut.context.DefaultBeanContext$$Lambda$389)
accept:176, ReferencePipeline$2$1 (java.util.stream)
accept:195, ReferencePipeline$3$1 (java.util.stream)
accept:177, ReferencePipeline$2$1 (java.util.stream)
forEachFrom:1037, ConcurrentLinkedQueue (java.util.concurrent)
forEachRemaining:894, ConcurrentLinkedQueue$CLQSpliterator (java.util.concurrent)
copyInto:484, AbstractPipeline (java.util.stream)
wrapAndCopyInto:474, AbstractPipeline (java.util.stream)
evaluateSequential:913, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:578, ReferencePipeline (java.util.stream)
findBeanCandidates:1389, DefaultBeanContext (io.micronaut.context)
findBeanCandidates:241, DefaultApplicationContext (io.micronaut.context)
isCandidatePresent:2617, DefaultBeanContext (io.micronaut.context)
containsBean:570, DefaultBeanContext (io.micronaut.context)
containsBean:355, BeanDefinitionRegistry (io.micronaut.context)
matchesPresenceOfBeans:529, RequiresCondition (io.micronaut.context)
processPostStartRequirements:198, RequiresCondition (io.micronaut.context)
matches:101, RequiresCondition (io.micronaut.context)
isEnabled:53, AbstractBeanContextConditional (io.micronaut.context)
isEnabled:89, AbstractBeanDefinition (io.micronaut.context)
lambda$findBeanCandidates$34:1388, DefaultBeanContext (io.micronaut.context)
test:-1, 1690101810 (io.micronaut.context.DefaultBeanContext$$Lambda$389)
accept:176, ReferencePipeline$2$1 (java.util.stream)
accept:195, ReferencePipeline$3$1 (java.util.stream)
accept:177, ReferencePipeline$2$1 (java.util.stream)
forEachFrom:1037, ConcurrentLinkedQueue (java.util.concurrent)
forEachRemaining:894, ConcurrentLinkedQueue$CLQSpliterator (java.util.concurrent)
copyInto:484, AbstractPipeline (java.util.stream)
wrapAndCopyInto:474, AbstractPipeline (java.util.stream)
evaluateSequential:913, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:578, ReferencePipeline (java.util.stream)
findBeanCandidates:1389, DefaultBeanContext (io.micronaut.context)
findBeanCandidates:241, DefaultApplicationContext (io.micronaut.context)
findBeanCandidates:277, DefaultApplicationContext (io.micronaut.context)
isCandidatePresent:2617, DefaultBeanContext (io.micronaut.context)
containsBean:570, DefaultBeanContext (io.micronaut.context)
containsBean:355, BeanDefinitionRegistry (io.micronaut.context)
matchesPresenceOfBeans:529, RequiresCondition (io.micronaut.context)
processPostStartRequirements:198, RequiresCondition (io.micronaut.context)
matches:101, RequiresCondition (io.micronaut.context)
isEnabled:53, AbstractBeanContextConditional (io.micronaut.context)
isEnabled:89, AbstractBeanDefinition (io.micronaut.context)
lambda$findBeanCandidates$34:1388, DefaultBeanContext (io.micronaut.context)
test:-1, 1690101810 (io.micronaut.context.DefaultBeanContext$$Lambda$389)
accept:176, ReferencePipeline$2$1 (java.util.stream)
accept:195, ReferencePipeline$3$1 (java.util.stream)
accept:177, ReferencePipeline$2$1 (java.util.stream)
forEachFrom:1037, ConcurrentLinkedQueue (java.util.concurrent)
forEachRemaining:894, ConcurrentLinkedQueue$CLQSpliterator (java.util.concurrent)
copyInto:484, AbstractPipeline (java.util.stream)
wrapAndCopyInto:474, AbstractPipeline (java.util.stream)
evaluateSequential:913, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:578, ReferencePipeline (java.util.stream)
findBeanCandidates:1389, DefaultBeanContext (io.micronaut.context)
findBeanCandidates:241, DefaultApplicationContext (io.micronaut.context)
findConcreteCandidateNoCache:2137, DefaultBeanContext (io.micronaut.context)
lambda$findConcreteCandidate$57:2127, DefaultBeanContext (io.micronaut.context)
apply:-1, 893591815 (io.micronaut.context.DefaultBeanContext$$Lambda$385)
lambda$compute$0:721, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
apply:-1, 93740343 (io.micronaut.core.util.clhm.ConcurrentLinkedHashMap$$Lambda$365)
computeIfAbsent:1705, ConcurrentHashMap (java.util.concurrent) [1]
compute:733, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
computeIfAbsent:710, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
findConcreteCandidate:2126, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1898, DefaultBeanContext (io.micronaut.context)
findBean:1062, DefaultBeanContext (io.micronaut.context)
lambda$findBeanForField$14:1428, AbstractBeanDefinition (io.micronaut.context)
resolveBean:-1, 1489099273 (io.micronaut.context.AbstractBeanDefinition$$Lambda$438)
resolveBeanWithGenericsForField:1753, AbstractBeanDefinition (io.micronaut.context)
findBeanForField:1427, AbstractBeanDefinition (io.micronaut.context)
getBeanForField:1376, AbstractBeanDefinition (io.micronaut.context)
getBeanForField:1156, AbstractBeanDefinition (io.micronaut.context)
injectBean:-1, $AfterCommitExecutorDefinition (com.the.jam.feature.core.transaction)
build:-1, $AfterCommitExecutorDefinition (com.the.jam.feature.core.transaction)
doCreateBean:1560, DefaultBeanContext (io.micronaut.context)
createAndRegisterSingleton:2279, DefaultBeanContext (io.micronaut.context)
getBeanForDefinition:1948, DefaultBeanContext (io.micronaut.context)
getBeanInternal:1923, DefaultBeanContext (io.micronaut.context)
getBean:1042, DefaultBeanContext (io.micronaut.context)
getBeanForField:1383, AbstractBeanDefinition (io.micronaut.context)
getBeanForField:1156, AbstractBeanDefinition (io.micronaut.context)
injectBean:-1, $AfterCommitInterceptorDefinition (com.the.jam.feature.core.transaction)
build:-1, $AfterCommitInterceptorDefinition (com.the.jam.feature.core.transaction)
doCreateBean:1560, DefaultBeanContext (io.micronaut.context)
addCandidateToList:2604, DefaultBeanContext (io.micronaut.context)
getBeansOfTypeInternal:2501, DefaultBeanContext (io.micronaut.context)
getBeansOfType:882, DefaultBeanContext (io.micronaut.context)
lambda$getBeansOfTypeForConstructorArgument$10:1096, AbstractBeanDefinition (io.micronaut.context)
resolveBean:-1, 991806841 (io.micronaut.context.AbstractBeanDefinition$$Lambda$427)
resolveBeanWithGenericsFromConstructorArgument:1734, AbstractBeanDefinition (io.micronaut.context)
getBeansOfTypeForConstructorArgument:1091, AbstractBeanDefinition (io.micronaut.context)
getBeanForConstructorArgument:963, AbstractBeanDefinition (io.micronaut.context)
build:-1, $$DummyRabbitImplDefinition$InterceptedDefinition (com.the.jam.feature.rabbit.service)
doCreateBean:1560, DefaultBeanContext (io.micronaut.context)
addCandidateToList:2604, DefaultBeanContext (io.micronaut.context)
getBeansOfTypeInternal:2524, DefaultBeanContext (io.micronaut.context)
getBeansOfType:865, DefaultBeanContext (io.micronaut.context)
getBeansOfType:594, DefaultBeanContext (io.micronaut.context)
getBeanRegistrations:351, DefaultBeanContext (io.micronaut.context)
initializeEventListeners:1193, DefaultBeanContext (io.micronaut.context)
readAllBeanDefinitionClasses:2417, DefaultBeanContext (io.micronaut.context)
start:201, DefaultBeanContext (io.micronaut.context)
start:187, DefaultApplicationContext (io.micronaut.context)
startApplicationContext:253, AbstractMicronautExtension (io.micronaut.test.extensions)
beforeClass:174, AbstractMicronautExtension (io.micronaut.test.extensions)
beforeAll:43, MicronautJunit5Extension (io.micronaut.test.extensions.junit5)
lambda$invokeBeforeAllCallbacks$8:361, ClassTestDescriptor (org.junit.jupiter.engine.descriptor)
execute:-1, 1891502635 (org.junit.jupiter.engine.descriptor.ClassTestDescriptor$$Lambda$270)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
invokeBeforeAllCallbacks:361, ClassTestDescriptor (org.junit.jupiter.engine.descriptor)
before:197, ClassTestDescriptor (org.junit.jupiter.engine.descriptor)
before:77, ClassTestDescriptor (org.junit.jupiter.engine.descriptor)
lambda$executeRecursively$5:132, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, 680576081 (org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$220)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$7:125, NodeTestTask (org.junit.platform.engine.support.hierarchical)
invoke:-1, 558187323 (org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$219)
around:135, Node (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$8:123, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, 889729797 (org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$218)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
executeRecursively:122, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:80, NodeTestTask (org.junit.platform.engine.support.hierarchical)
accept:-1, 1527430292 (org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$224)
forEach:1540, ArrayList (java.util)
invokeAll:38, SameThreadHierarchicalTestExecutorService (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$5:139, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, 680576081 (org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$220)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$7:125, NodeTestTask (org.junit.platform.engine.support.hierarchical)
invoke:-1, 558187323 (org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$219)
around:135, Node (org.junit.platform.engine.support.hierarchical)
lambda$executeRecursively$8:123, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:-1, 889729797 (org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$218)
execute:73, ThrowableCollector (org.junit.platform.engine.support.hierarchical)
executeRecursively:122, NodeTestTask (org.junit.platform.engine.support.hierarchical)
execute:80, NodeTestTask (org.junit.platform.engine.support.hierarchical)
submit:32, SameThreadHierarchicalTestExecutorService (org.junit.platform.engine.support.hierarchical)
execute:57, HierarchicalTestExecutor (org.junit.platform.engine.support.hierarchical)
execute:51, HierarchicalTestEngine (org.junit.platform.engine.support.hierarchical)
execute:229, DefaultLauncher (org.junit.platform.launcher.core)
lambda$execute$6:197, DefaultLauncher (org.junit.platform.launcher.core)
accept:-1, 40472007 (org.junit.platform.launcher.core.DefaultLauncher$$Lambda$177)
withInterceptedStreams:211, DefaultLauncher (org.junit.platform.launcher.core)
execute:191, DefaultLauncher (org.junit.platform.launcher.core)
execute:128, DefaultLauncher (org.junit.platform.launcher.core)
startRunnerWithArgs:69, JUnit5IdeaTestRunner (com.intellij.junit5)
startRunnerWithArgs:47, IdeaTestRunner$Repeater (com.intellij.rt.execution.junit)
prepareStreamsAndStart:242, JUnitStarter (com.intellij.rt.execution.junit)
main:70, JUnitStarter (com.intellij.rt.execution.junit)
```
</p>
</details>

And here is the important part of this stacktrace:

```
computeIfAbsent:1760, ConcurrentHashMap (java.util.concurrent) [2]
compute:733, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
computeIfAbsent:710, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
findConcreteCandidate:2126, DefaultBeanContext (io.micronaut.context)
[...]
computeIfAbsent:1705, ConcurrentHashMap (java.util.concurrent) [1]
compute:733, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
computeIfAbsent:710, ConcurrentLinkedHashMap (io.micronaut.core.util.clhm)
findConcreteCandidate:2126, DefaultBeanContext (io.micronaut.context)
[...]
```

For both `computeIfAbsent()` invocations **this is the same map object**, and both come from `findConcreteCandidate()` -> `ConcurrentLinkedHashMap.compute()`.

It's said on `ConcurrentMap#computeIfAbsent()`: **The mapping function should not modify this map during computation**, what's obviously not fulfilled by Micronaut, because from one computation comes another computation for the same map.

This is not even a problem of having  a singleton bean resolving another bean that is in creation, or other recursive-dependency problems between beans. The interesting part is in `ConcurrentHashMap.computeIfAbsent()` code:

```java
    public V computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction) {
        if (key == null || mappingFunction == null)
            throw new NullPointerException();
        int h = spread(key.hashCode());
        V val = null;
        int binCount = 0;
        for (Node<K,V>[] tab = table;;) {
            Node<K,V> f; int n, i, fh; K fk; V fv;
            if (tab == null || (n = tab.length) == 0)
                tab = initTable();
            else if ((f = tabAt(tab, i = (n - 1) & h)) == null) {
                Node<K,V> r = new ReservationNode<K,V>();
                synchronized (r) {
                    if (casTabAt(tab, i, null, r)) {
                        binCount = 1;
                        Node<K,V> node = null;
                        try {
                            if ((val = mappingFunction.apply(key)) != null)
                                node = new Node<K,V>(h, key, val);
```

`h` is calculated from the key hashcode, and then `i = (n - 1) & h` what is the same number for the same hashcode and table size (`n`). In such scenario the implementation creates under `i` element `ReservationNode` and goes to the computation method. If the computation method calls again `computeIfAbsent()` on the same map and **it happens that newly calculated `i` is the same as in the outer call** it fails with an exception because the index is already occupied by the `ReservationNode`.

And this happens exactly in my scenario. In the first `computeIfAbsent()` call I have a key of `BeanKey` type from which the following values are calculated in `computeIfAbsent()` function:

```
@Named('transactionalAfterCommitExecutor') com.the.jam.feature.core.transaction.TransactionalAfterCommitExecutor
hashcode: 1040866384
h=1040867930
n=32
i=26
```

And in the inner call I have another `BeanKey` with different hash, but here are values calculated:

```
@Named('default') io.micronaut.configuration.hibernate.jpa.JpaConfiguration$EntityScanConfiguration
hashcode: -1298771444
h=848748698
n=32
i=26
```

These two beans do not collide with each other in any way, and the only problem here is unfortunate hashcode collision, which produce the same `i` value for both calls, and of course misuse of `computeIfAbsent()` which can recursively invoke another `computeIfAbsent()` on the same map.

This also explains why it happens randomly. It depends on the hashcode which is originally calculated from the identity hash code, which is basically random.

**Comment by graemerocher** [comment]
#2140 provides a reproducible example so I will be looking at that one tomorrow. However since this report doesn't include one it is hard to say whether it would resolve it. The actual cause is that it is trying to create the same been twice within the same bean creation graph. So we should probably catch this error and rethrow it as a `CircularDependencyException` with more information which would help you debug the issue further as you say you can't attach an example.

I will look to do that as part of #2140 

Changing to a synchronized map is not the solution as would just change the behahviour to instead result in a potential deadlock IMO

**Comment by jameskleeh** [comment]
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/2140

**Comment by l0co** [comment]
OK, I'll wait for #2140 resolution... but:

1. The problem there is different and the execution path is different. In #2140 you do the same from `RefreshScope.get()` which is different `ConcurrentHashMap` and different scenario. In a nuthel: I don't believe solving #2140 will solve this problem.
2. In my opinion, you shouldn't wrap this exception in `CircularDependencyException` because this exception happens randomly and depends on the collision on hashcode, as described previously. So,  what would you tell the user with this exception? Sometimes there's a circular dependency in your app, and sometimes not?
3. Continuing the thought from the previous point. The exception only happens on hashcode collision, and otherwise the application doesn't have any problems with start, no circular dependencies, etc. So, the problems seems to be dependant only to the `ConcurrentHashMap` implementation which does the things in its way. If you would have used something different, for example `SynchronizedMap`, or not to use `computeIfAbsent()` at all, everything had worked. In my opinion the problem is fixable here and the bean structure is OK.

**Comment by l0co** [comment]
Actually, the workaround is:

```java
public final class ConcurrentLinkedHashMap<K, V> {
	private V compute(final K key, final Function<? super K, ? extends V> mappingFunction, boolean onlyIfAbsent) {

		// ... instead of data.computeIfAbsent()
		Node<K, V> prior = data.get(key);
		synchronized (this) {
			if (prior==null) {
				prior = f.apply(key);
				if (prior!=null)
					data.put(key, prior);
			}
		}

```

**Comment by graemerocher** [comment]
The issue #2140 has been resolved. Whilst I appreciate your suggestions, the reason why `computeIfAbsent` needs to be atomic is that if it were not then you could get the same singleton bean constructed twice, which is clearly undesirable.

The underlying issue which is resolved for #2140 is that there is a bean that is currently in the middle of creation that is then requested again. Since it has not yet been registered as a singleton in the map this causes another call to `computeIfAbsent`. 

This should not happen however as we have special handling for "In Flight" beans. Part of the fix for #2140 identified a problematic scenario. It may well also resolve your case, however without a reproducible example we cannot say for sure.

As to why it happens randomly it is likely that in some cases the beans are created in a different order since beans themselves are stored in hashmaps/concurrentsets there is no guarantees about what order beans will be created in. The case that works it is likely that the `DataSource` was created already whilst the case that fails the `DataSource` is not recreated yet and hits the problem.

Again that is my guess but without an example that we can see to debug the problematic behaviour we cannot say for sure. Hopefully the fix for #2140 helps.

**Comment by l0co** [comment]
OK, I'll try to do some tests when 1.2.3 will be released.

Unfortunetely I cannot reproduce this error in the simple example app. This is something that happens only with my beans config. I think the problem is inside `@Around` advices and the interceptor dependencies. The recursive map update happens only for `MethodInterceptor` which has further dependencies on other beans.

**Comment by l0co** [comment]
It looks in 1.2.3 the "Recursive update" error may still happen in the same way as in 1.2.2.

**Comment by l0co** [comment]
Some final thoughts. The error happens for me in the following scenario:

```java
@Around
@Type(AfterCommitInterceptor.class)
public @interface AfterCommit {}

@Singleton
public class AfterCommitInterceptor implements MethodInterceptor<Object, Object>, Ordered {
  @Inject protected IAfterCommitExecutor afterCommitExecutor;
  // ...
}

@Singleton @Requires(beans = PlatformTransactionManager.class)
public class TransactionalAfterCommitExecutor implements IAfterCommitExecutor {

   @Transactional
   void doSomething() {
      // ...
   }

}

@Singleton
public class SomeBean {

   @Transactional @AfterCommit
   void doSomething() {
      // ...
   } 

}
```

So, there's an AOP interceptor which refers to some `@Transactional` bean, and then there's a bean which uses at the same time this AOP interceptor and the `@Transactional` interceptor. However, I cannot reproduce this exception in separated environment with the same configuration.

### Workaround

For someone looking for workaround in similar cases, I've fixed this by making the problematic bean lazy:

```java
@Singleton
public class AfterCommitInterceptor implements MethodInterceptor<Object, Object>, Ordered {
  private IAfterCommitExecutor _afterCommitExecutor;
  @Inject protected BeanContext beanContext;

  protected IAfterCommitExecutor afterCommitExecutor() {
	if (_afterCommitExecutor ==null)
		_afterCommitExecutor = beanContext.getBean(IAfterCommitExecutor.class);

	return _afterCommitExecutor;
  }

}
```

**Comment by lightbody** [comment]
We're on 1.2.6 and get this error maybe 10% of the time we start up as well.

**Comment by stepanv** [comment]
I'm on 1.3.2 and I just started facing this intermittent "Recursive Update" issue as well.

**Comment by graemerocher** [comment]
provide an example and we can take a look
