### ISSUE TITLE
Traces for request not aggregated when using micronaut with kotlin coroutines

### ISSUE THREAD

**Issue by bjor-joh** [micronaut-projects/micronaut-core#4120]
I'm trying to setup distributed tracing for my micronaut service with GCP cloud trace. Service is written in kotlin and uses coroutines.

When I make a request to my application I can see the traces in the gcp-console. But any http call made by my application to subsequent services ends up as different traces instead of spans within one trace. If I look at the trace headers I can see that it seems to switch trace id when switching threads, instead of propagating the same trace-id throughout the entire request. 

This is how it looks in the gcp console. 
![QIbQx](https://user-images.githubusercontent.com/53463827/93430757-74cb1980-f8c3-11ea-8491-370af2ab19c9.png)

Sample application: https://github.com/bjor-joh/micronaut-distributed-tracing

**Comment by graemerocher** [comment]
Probably fixed by https://github.com/micronaut-projects/micronaut-core/pull/3921

**Comment by jameskleeh** [comment]
@bjor-joh Can you test with Micronaut 2.1?

**Comment by bjor-joh** [comment]
Still getting a new trace whenever I start a new Coroutine. Bumped versions in sample project.

**Comment by samuellobatozup** [comment]
Hi @bjor-joh. Do you have some workaround for this issue? I have same problem and dont know how to solve.
I'll apreciete your answer.

**Comment by ghost** [comment]
It appears that the context of the incoming http request does not get passed around when suspending/resuming coroutines.

Anything we can do/configure to get this to work?

**Comment by drmaas** [comment]
@jameskleeh I tried with the latest (2.5.x branch) and I am seeing a related failure, where suspension points "lose track" of any MDC attributes (and probably thread context in general). 

Specifically - this test case fails, and shouldn't, because the tracing project is included in the test scope. https://github.com/drmaas/micronaut-core/blob/fix-mdc-controller-suspend/test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendControllerSpec.kt#L238

https://github.com/drmaas/micronaut-core/blob/fix-mdc-controller-suspend/test-suite-kotlin/build.gradle#L44

I am not sure if this is the same or a different issue. Happy to open a new issue if you want.
