### ISSUE TITLE
httpClient service call timeout  problem

### ISSUE THREAD

**Issue by gitjxm** [micronaut-projects/micronaut-core#5546]
I started a de-task service to register with consul
![image](https://user-images.githubusercontent.com/41097032/120998729-ef71f700-c7ba-11eb-9add-9f5db6f54280.png)
![image](https://user-images.githubusercontent.com/41097032/120998739-f3057e00-c7ba-11eb-8fc5-1a93cb5252e7.png)

I started a test service to register with consul,through client configure call de task
![image](https://user-images.githubusercontent.com/41097032/120998782-fbf64f80-c7ba-11eb-977d-6c9ceda9338c.png)
![image](https://user-images.githubusercontent.com/41097032/120998804-01539a00-c7bb-11eb-837a-9e3ee63fc2d1.png)

Call five times, there is a timeout, I do not know where the consul and client timeout
![image](https://user-images.githubusercontent.com/41097032/120998909-192b1e00-c7bb-11eb-9650-f29a6e59be3d.png)

**Comment by gitjxm** [comment]
The timeout request didn't call the de-task service, so I'm sure it's a consul or client problem。There's a 20% chance of timeout

**Comment by gitjxm** [comment]
![image](https://user-images.githubusercontent.com/41097032/121001914-593fd000-c7be-11eb-82be-7beff07cc84a.png)

**Comment by gitjxm** [comment]
hello
After testing, the httpclient request thread pool is not recycled by default, resulting in httpclient request timeout, In this case, the thread is recycled, but the request times out,The next request will not time out, When the threads in the thread pool are used up, the request will time out again
```text
micronaut:
  netty:
    event-loops:
      default:
        num-threads: 10
        prefer-native-transport: true
```
The number of netty test threads can only alleviate the request timeout interval, but can not solve the problem
I don't know how to solve this problem

**Comment by graemerocher** [comment]
provide an example with clear steps to reproduce

**Comment by gitjxm** [comment]
hello
https://github.com/gitjxm/micronaut-client
There are two projects in it
![image](https://user-images.githubusercontent.com/41097032/121177449-fcace580-c88f-11eb-808d-cd682b898819.png)
http://localhost:8081/client/hello/zhang

**Comment by gitjxm** [comment]
hello 
sorry.There is a problem with the example I gave, which has been corrected
I saw a similar answer to my question,But there is no solution
 https://github.com/micronaut-projects/micronaut-core/issues/5270
I tried to use the version 2.3.4 of MICRONAUT, which also has this problem.I'm not sure if this problem is netty thread recycling problem. I'm a little skeptical

**Comment by yawkat** [comment]
is there a way to reproduce this without consul?

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
