### ISSUE TITLE
Bug: Version 3.0.0+ changed the way the proxy is injected in @Transactional

### ISSUE THREAD

**Issue by weesftw** [micronaut-projects/micronaut-core#7489]
### Expected Behavior

In versions prior to 3.0, the way the `@Transactional` proxy is injected using `spring-jdbc` with `micronaut-spring` has changed its behavior. Before it was possible to wrapper and place a transaction responsible for several steps inside a flow (for example, using workflow pattern) and now this is not possible anymore.

### Actual Behaviour

![Untitled](https://user-images.githubusercontent.com/58608499/170038485-b07e25d6-f0aa-40b9-9ba7-6cd19776e72d.jpg)

### Steps To Reproduce

In `target/classes/` you can see the proxy generation and that there is possibly something weird.

### Environment Information

Ubuntu 20.04
JDK: 11

### Example Application

https://github.com/weesftw/micronaut-transaction-failed/blob/master/src/main/java/my/transaction/app/workflow/definition/TransactionalActityItem.java

### Version

3.4.4

**Comment by graemerocher** [comment]
might be related to annotation inheritance, what happens if you declare `@Transactional` on the classes that extend from your type?

**Comment by weesftw** [comment]
@graemerocher 

Yep, works in this case. I would like to perform a delegate instead of extending, or is it no longer possible?

**Comment by graemerocher** [comment]
so, in the previous version of Micronaut this caused issues when people wanted to extend and override so this changed in Micronaut 3.x and the new behaviour is more flexible. However if you do want an annotation to be inherited that is not (like `@Transactional`) you have to make a meta annotation:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@Documented
@Transactional
@Inherited
public @interface InheritedTransactional {
}
```

**Comment by weesftw** [comment]
@graemerocher 

I did some testing and the problem persists, I updated the [example](https://github.com/weesftw/micronaut-transaction-failed/commit/0aaee5c7aba394b2f12a7ff61c0f4dd84cdb4e63) repository.

**Comment by viniciusxyz** [comment]
@graemerocher  I performed the same test as @weesftw  and got the same problem, even creating the new annotation with all meta data informed it still doesn't work :/

I don't know if it helps, but here's a print of the compiled classes and the class we're using.

![image](https://user-images.githubusercontent.com/19265464/170103101-1b9ec833-fb50-4887-a98a-c2fc334f9662.png)

**Comment by dstepanov** [comment]
You might try to use Micronaut's `@Transactional` or directly `@TransactionalAdvice` which all of them are remapped to.

**Comment by graemerocher** [comment]
Hmm actually this is not related to inheritance, you have a very weird model where you are using generic arguments `TransactionalActityItem<INPUT, OUTPUT>` but then injecting the type with raw arguments:

```java
    @Inject
    public DepositController(TransactionalActityItem activityMakeDeposity) {
        this.activityMakeDeposity = activityMakeDeposity;
    }
```

I made the assumption inheritance was involved because of the presence of the generics which don't seem to make much sense. Also you are directly instantiating the bean:

```java
    @Bean
    @Singleton
    public TransactionalActityItem<Deposit, Void> provideTxActivity() {
        return new TransactionalActityItem<>(activityMakeDeposity);
    }
```

So in this case to make it would you would need to declare `@Transactional` on the factory method:

```java
    @Bean
    @Singleton
   @Transactional
    public TransactionalActityItem<Deposit, Void> provideTxActivity() {
        return new TransactionalActityItem<>(activityMakeDeposity);
    }
```

**Comment by viniciusxyz** [comment]
@dstepanov These annotations are not available in the project, I believe it is because we are using spring jdbc

**Comment by viniciusxyz** [comment]
@graemerocher Sorry that generics point was an error in inject, I fixed it for injection as TransactionalActityItem<Deposit, Void> and it still didn't work with the new annotation, I performed a second test adding the annotation about the bean in the factory just like you showed, but strangely that didn't work either

**Comment by weesftw** [comment]
> Hmm actually this is not related to inheritance, you have a very weird model where you are using generic arguments `TransactionalActityItem<INPUT, OUTPUT>` but then injecting the type with raw arguments:
> 
> ```java
>     @Inject
>     public DepositController(TransactionalActityItem activityMakeDeposity) {
>         this.activityMakeDeposity = activityMakeDeposity;
>     }
> ```
> 
> I made the assumption inheritance was involved because of the presence of the generics which don't seem to make much sense. Also you are directly instantiating the bean:
> 
> ```java
>     @Bean
>     @Singleton
>     public TransactionalActityItem<Deposit, Void> provideTxActivity() {
>         return new TransactionalActityItem<>(activityMakeDeposity);
>     }
> ```
> 
> So in this case to make it would you would need to declare `@Transactional` on the factory method:
> 
> ```java
>     @Bean
>     @Singleton
>    @Transactional
>     public TransactionalActityItem<Deposit, Void> provideTxActivity() {
>         return new TransactionalActityItem<>(activityMakeDeposity);
>     }
> ```

@graemerocher 

Thank you so much for taking the time to resolve this issue. Unfortunately, I did what you said but the transaction is still not able to handle multiple steps within a flow as it did in version 2.5.x.

**Comment by weesftw** [comment]
hey @graemerocher,

Any update on this issue? or we can consider that this is the behavior expected by the Micronaut.

**Comment by azakrytnoi** [comment]
This is 100% user issue: no translation demarcation provided. When adding @Transactional to proper places:
- for DepositService.makeDeposit ```@Transactional(propagation = Propagation.REQUIRES_NEW)``` 
- for both *Repository ```@Transactional(propagation = Propagation.MANDATORY)```
Then new transaction is created at main service invocation and repository invocations shares the same transaction.

This behaviour is standard and was not changed forever.

**Comment by viniciusxyz** [comment]
@azakrytnoi I don't understand your point, isn't it appropriate to use @Transactional over a decorator ?  why ?  this is what we did in version 2.5.x and it worked, this stopped working after upgrading to 3.x.x.

**Comment by weesftw** [comment]
hey @azakrytnoi thanks for comment! I'm using a `pattern` to wrap this transaction... I have several steps that access the database and insert different data and I need **atomicity**. In the previous version of Micronaut it worked perfectly, now with the migration from `3.x`, the proxy that was on top of the pattern broke... unfortunately your help was not enough.

@graemerocher,
With the version change, has there been any change in proxy behavior (in general)? I would like to contribute.
